### ISSUE TITLE
M1 Mac Compatibility Issues

### ISSUE THREAD

**Issue by ccamacho89** [WEHI-labatlab/HandE#13]
I'm having trouble starting up HandE on a Mac M1; it seems the issue lies in building the numpy library. I've tried downloading numpy to the heGUI environment directly using this link (https://gist.github.com/MarkDana/a9481b8134cf38a556cf23e1e815dafb) but without success. Are there extra configuration parameters we need to run the HandE application on M1?

**Comment by christianrickert** [comment]
Hello @ccamacho89,

I was able to reproduce your issue: it looks like `pip` has an issue with resolving dependencies in the latest version due to a [bug](https://github.com/conda/conda/issues/10807).
The missing `numpy` dependency can be resolved by providing an explicit dependency for conda, and the `pip` regression by pinning the version number to a previous version.

I have altered the `environment.yml` to include `pip` and `numpy` explicitly:

```YAML
name: heGUI
channels:
- conda-forge
- defaults
dependencies:
- python=3.8
- tk=8.6.11
- numpy=1.23.3
- pyqt=5.15.7
- pip=20.3.4
- pip:
    - magicgui[pyqt5]
    - napari[all]==0.4.16
    - python-dotenv==0.19.0
    - scikit-image==0.19.3
    - imagecodecs==2021.8.26
    - git+https://github.com/WEHI-labatlab/mibilib.git@master
```

However, I still run into an issue with a missing installation candidate for `pandas`:
```zsh
ERROR: Could not find a version that satisfies the requirement pandas==1.2.3 (from mibilib)
ERROR: No matching distribution found for pandas==1.2.3
```

This error showed up on my MacOS/M1-Pro, but not on Windows 10/Intel.

@yokotenka I can see that there is an installation candidate (v.1.4.4) available for ARM64,
see [Anaconda package list](https://docs.continuum.io/anaconda/packages/py3.8_osx-arm64/).
Do you think it would be possible to bump the version requirement in your `mibilib` from 1.2.3 to 1.4.4?

**Comment by yokotenka** [comment]
Apologies for the late reply. Thank you for looking into this issue @christianrickert.

I have created a new branch [https://github.com/WEHI-labatlab/HandE/tree/issue_13](url) with your proposed changes. Since I don't have access to a M1-Pro macbook, would you be able to see if this works on the M1? 

If all goes well, then I can merge this branch to the main. 

Thank you,
Kenta

**Comment by christianrickert** [comment]
I've added the pip version number to be able to run the installation of the environment, see the aforementioned `pip` bug:
```yaml
- pip=20.3.4
```

With the current branch update for #13, I get the next issue:
```zsh
ERROR: No matching distribution found for scikit-learn==0.23.2
```

I'd suggest to bump the versions until we run into any issues?

**Comment by yokotenka** [comment]
I've bumped the version of scikit-learn up to the most recent version 1.1.3 in my fork of the mibilib. 
Let me know how it goes.

**Comment by christianrickert** [comment]
I've tested the latest updates without success: `pip` is basically running in circles and resolving dependencies for 15 minutes and longer - after which I stopped the installation procedure.

I would suggest to revisit this issue in the future since it will likely be resolved upstream with a newer version of `pip`.

**Comment by srivarra** [comment]
I was able to successfully build and run HandE natively on Apple Silicon (M1 Max).

I changed the requirements in `environment.yml` to favor the latest pre-compiled binaries on Anaconda instead of PYPI:

```yaml
name: heGUI
channels:
- conda-forge
- defaults
dependencies:
- python=3.8
- pip
- python-dotenv
- pyqt
- numpy
- imagecodecs
- tifffile
- scikit-image
- magicgui[pyqt5]
- napari[all]
- pip:
    - ../mibilib/
```

where `../mibilib/` is a local installation of [WEHI's forked `mibilib`](https://github.com/WEHI-labatlab/mibilib).


With respect to `mibilib` I made the requirements in `setup.py` much more relaxed.

```python
setup(name='mibilib',
      author='IONpath, Inc.',
      author_email='support@ionpath.com',
      version='1.4.2',
      url='https://github.com/ionpath/mibilib',
      description='Python utilities for IONpath MIBItracker and MIBItiff data',
      license='GNU General Public License v3.0',
      python_requires='~=3.8',
      install_requires=[
          'matplotlib',
          'numpy',
          'pandas',
          'pillow',
          'requests',
          'scikit-image',
          'scikit-learn',
          'tifffile',
          'tqdm',
      ],
      packages=['mibitracker', 'mibidata']
     )
```

Hope this is helpful.
